const nodemailer = require("nodemailer")
const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: "petter@test.com", // this mail send mail id
    pass: "aaaa bbbb cccc dddd", // this is the pass which is generated by the send eamil id
  },
  secure: false,
  port: 25,
  tls: {
    rejectUnauthorized: false,  
  },
});

// Define the email options
const mailOptions = {
  from: "petter@test.com",
  to: "sem@test.com",
  subject: `Apply for the exam leave`,
  html: `<p>i want to for day of leave</p>`,
};

// Send the email
transporter.sendMail(mailOptions, (error, info) => {
  if (error) {
    return console.error("Error:", error.message);
  }
});